# Generated by Django 4.0.5 on 2022-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='type_old',
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='type',
            field=models.CharField(choices=[('Task', 'задача'), ('Bug', 'ошибка'), ('Enhancement', 'улучшение')], max_length=30),
        ),
    ]
