# Generated by Django 4.0.5 on 2022-07-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_type_task_type_old_alter_tasktype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_old', to='webapp.tasktype', verbose_name='Тип'),
        ),
    ]
