# Generated by Django 4.0.5 on 2022-07-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_task_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='types', to='webapp.tasktype'),
        ),
    ]
