# Generated by Django 4.0.5 on 2022-07-12 09:28

from django.db import migrations
def transfer(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.type.add(task.type_old)

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_task_type'),
    ]

    operations = [
        migrations.RunPython(transfer)
    ]
