# Generated by Django 4.0.5 on 2022-07-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_task_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проэкт', 'verbose_name_plural': 'Проэкты'},
        ),
    ]
